### PR TITLE
Fix build and populate index in parallel

### LINKED ISSUE #84: Update Cargo deps for Pear/Rocket Rust Nightly regression workaround
Hello again. I recently had to start from scratch with Polaris again and it wouldn't build on Linux this time around even though it had built successfully on the same hardware a couple months back. Here's why:

https://github.com/rust-lang/rust/pull/73293

This change to Rust created a regression in Pear (a Rocket subdependency), but thankfully a bugfix has been released. After following the directions in the above PR to take advantage of the bugfix, the build succeeded.

Basically, we need to update Pear to its latest version in the `Cargo.lock` file for Polaris to successfully build with Rust Nightly.

Something like `cargo update -p pear && cargo update` should do it, then we can put up a PR with the Cargo file changes.

Would you like to handle this, or for me to put up a PR?

### LINKED ISSUE #85: could not compile rocket_http
Hello,

I wanted to try out this under Debian Buster (in an LXC container, but that doesn't really matter I suppose...), and got the following fail message:

> error: proc macro panicked
>    --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/rocket_http-0.4.5/src/parse/uri/parser.rs:119:34
>     |
> 119 |             let path_and_query = pear_try!(path_and_query(is_pchar));
>     |                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>     |
>     = help: message: called `Option::unwrap()` on a `None` value
>     = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)
> 
> error: aborting due to previous error
> 
> error: could not compile `rocket_http`.
> 
> To learn more, run the command again with --verbose.
> warning: build failed, waiting for other jobs to finish...
> error: build failed
> make: *** [Makefile:7: build] Error 101

Rust is nightly (installed as per your recommended command):

> curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain nightly

Thank You!

### PR DESCRIPTION
**Pull request by lnicola**
Fixes #85 
Fixes #84 

CC @eisengrau

### CODE REVIEW

**Comment by lnicola** [comment]
Some rough measurements:

```
[INFO] [src/index/update.rs:27] Library index update took 322.893 seconds

# rayon within a directory
[INFO] [src/index/update.rs:28] Library index update took 172.079 seconds

# rayon both within a directory and across directories
[INFO] [src/index/update.rs:28] Library index update took 49.357 seconds
```

I tried to drop the caches before the last measurement, but I'm not sure it worked (ZFS on Linux). Tested on a Celeron J1900.

File: src/index/update.rs [hunk 1]
```diff
@@ -322,8 +341,8 @@ pub fn populate(db: &DB) -> Result<()> {
 		Regex::new(&settings.index_album_art_pattern)?
 	};
 
-	let (directory_sender, directory_receiver) = channel();
-	let (song_sender, song_receiver) = channel();
+	let (directory_sender, directory_receiver) = crossbeam_channel::unbounded();
```
Comment (lnicola) [inline src/index/update.rs:344]: Switched to `crossbeam-channel` because it's `Sender` is `Sync` (and it's also faster and more reliable than the `std` one).

File: src/index/update.rs [hunk 2]
```diff
@@ -174,54 +184,64 @@ impl IndexUpdater {
...
+			let _guard = flame::start_guard("song_metadata");
+
+			path.to_str().and_then(|file_path_string| {
+				metadata::read(&path).map(|m| (file_path_string.to_owned(), m))
+			})
+		};
+		let song_tags = song_files
+			.into_par_iter()
+			.filter_map(song_metadata)
+			.collect::<Vec<_>>();
```
Comment (lnicola) [inline src/index/update.rs:201]: We could avoid the allocation here by doing a `fold`.

File: src/index/update.rs [hunk 3]
```diff
@@ -246,11 +266,10 @@ impl IndexUpdater {
...
 
 		// Populate subdirectories
-		for sub_directory in sub_directories {
-			self.populate_directory(Some(path), &sub_directory)?;
-		}
-
-		Ok(())
+		sub_directories
+			.into_par_iter()
+			.map(|sub_directory| self.populate_directory(Some(path), &sub_directory))
```
Comment (agersant) [inline src/index/update.rs:271]: Could we use `.for_each()` here instead of map and collect for more clarity? I'm also unsure how this `collect()` compacts the Iter of results into a single value.

File: src/index/update.rs (hunk 2 above)
Comment (agersant) [reply src/index/update.rs:201]: Good enough for me and very readable in this form

File: src/index/update.rs [hunk 4]
```diff
@@ -337,10 +356,13 @@ pub fn populate(db: &DB) -> Result<()> {
...
-		for target in mount_points.values() {
-			updater.populate_directory(None, target.as_path())?;
-		}
+		let updater = IndexUpdater::new(album_art_pattern, directory_sender, song_sender)?;
+		let mount_points = mount_points.values().collect::<Vec<_>>();
+		mount_points
+			.iter()
+			.par_bridge()
+			.map(|target| updater.populate_directory(None, target.as_path()))
+			.collect::<Result<()>>()?;
```
Comment (agersant) [inline src/index/update.rs:365]: This looks like the same `collect` magic! Does something `Into<Result>` for `Iter<Result>`?

**Comment by agersant** [comment]
Left one minor question before merging, but this is a great change! Very promising numbers - although I assume it might be especially beneficial on the lower end CPU.

File: src/index/update.rs (hunk 3 above)
Comment (lnicola) [reply src/index/update.rs:271]: I think it's the same as the similar Iterator method. It propagates one of the Err results (note how you were using ? before, exiting at the first error). With my other error printing change, we should get an error if the channel was closed. It probably doesn't matter much, but it seemed more clear to exit like this than to not handle the errors.

I'll add a comment here.

File: src/index/update.rs (hunk 4 above)
Comment (lnicola) [reply src/index/update.rs:365]: Same as above, it returns an error if one of the mounts failed.

**Comment by lnicola** [comment]
I think it's beneficial on slower drives because you get more IO operations at once. Even mechanical drives are fastest at 8 concurrent IOs or so.

On my CPU this still doesn't go above 50-80% overall usage (over the four coures), even with ZFS trying to uncompress the files.

File: src/index/update.rs (hunk 3 above)
Comment (lnicola) [reply src/index/update.rs:271]: See https://doc.rust-lang.org/stable/rust-by-example/error/iter_result.html#fail-the-entire-operation-with-collect, it's a less-known trick.

**Comment by eisengrau** [comment]
Hello,

So yesterday I added my collection of about 200k mp3 files at the time of opening #85. Unforunately after a couple of hours it 'timed out' so it idexed just a few folders of it. I clikced on scan now again, once I restarted the container, it is the same CPU usage as yesterday, around 3% max. The music collection is on ZFS on linux (LZ4 compression) with an i5-4590.

Maybe this will fix it. I'm eagerly waiting for a new build. :)

**Comment by lnicola** [comment]
Even if you closed the browser, the scan should have ran in the background (it runs periodically anyway).

> ZFS on linux

:smile:

**Comment by eisengrau** [comment]
It's definately doing something:
image
image

I'll get back and try to find some logs once it stops. Does the polaris binary generate any, or at the moment it just runs in the background once launched?

**Comment by lnicola** [comment]
> teddybear

:smile: 

> I'll get back and try to find some logs once it stops. Does the polaris binary generate any, or at the moment it just runs in the background once launched?

It doesn't write to a file, but to console. On my distro I see them with `journalctl` and in Docker `docker logs` probably works, but I'm not sure what Debian and LXC do.

**Comment by agersant** [comment]
> There's no logs for files scanned successfully
There is a log entry at the end of each scan, you've been using it for your benchmarks @lnicola :D

On Linux, running without the `-f` flag makes the output go to a `polaris.log` file under your `$XDG_CACHE_HOME` directory. Running with `-f` makes the process not daemonize and output to console.

**Comment by agersant** [comment]
As a datapoint @eisengrau, I run Polaris on a Raspberry Pi 3 with about 80k songs on a USB HDD and the initial indexing (cold cache) takes about 10-15 minutes IIRC.

**Comment by lnicola** [comment]
@agersant I'm curious what effect this PR has on that.

**Comment by eisengrau** [comment]
Ok, I ran polaris -f, I could now see what has stopped the scanning:

10:09:26 [ERROR] [src/index/mod.rs:90] Error while updating index: Invalid directory path

Could be directories/file names with accented/invalid characters?

**Comment by lnicola** [comment]
I think I fixed an issue causing it to give up on some errors, can you try with the latest version?

**Comment by eisengrau** [comment]
Should I git clone and recompile again, since previously I just unpacked the latest archive and used that.

**Comment by lnicola** [comment]
Clone, `cargo build --release` and take the binary from `target/release/polaris`.
